import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/common/Navbar'
import 'flowbite';
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Blog System',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}
        className={inter.className}>
        <Navbar />
        <div>
          {children}
        </div>
      </body>
    </html>
  )
}
